import { z } from 'zod';

import { REST_API, USERS_ROUTES } from '../../../api';
import { getEndpointDetails } from '../../../constants';
import { UserResponseSchema } from '../user.response';

export namespace RevokeUserSubscriptionCommand {
    export const url = REST_API.USERS.ACTIONS.REVOKE_SUBSCRIPTION;
    export const TSQ_url = url(':uuid');

    export const endpointDetails = getEndpointDetails(
        USERS_ROUTES.ACTIONS.REVOKE_SUBSCRIPTION(':uuid'),
        'post',
        'Revoke user subscription',
        { scope: 'revoke-subscription', kind: 'write' },
    );

    export const RequestParamSchema = z.object({
        uuid: z.uuid(),
    });

    export const RequestBodySchema = z.preprocess(
        (val) => val || {},
        z.object({
            revokeOnlyPasswords: z.optional(
                z
                    .boolean()
                    .default(false)
                    .describe(
                        'Optional. If true, only passwords will be revoked, without changing the short UUID (Subscription URL).',
                    ),
            ),
            shortUuid: z.optional(
                z
                    .string()
                    .min(6)
                    .max(48)
                    .describe(
                        'Optional. If not provided, a new short UUID will be generated by Remnawave. Please note that it is strongly recommended to allow Remnawave to generate the short UUID.',
                    ),
            ),
        }),
    );

    export const ResponseSchema = UserResponseSchema;

    export type RequestParam = z.infer<typeof RequestParamSchema>;
    export type RequestBody = z.infer<typeof RequestBodySchema>;
    export type Response = z.infer<typeof ResponseSchema>;
}
